version: '3.8'

networks:
  urbansend_network:
    driver: bridge
    name: urbansend_network

volumes:
  urbansend_redis_data:
    name: urbansend_redis_data
  urbansend_backend_data:
    name: urbansend_backend_data
  urbansend_backend_logs:
    name: urbansend_backend_logs

services:
  urbansend_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: urbansend_backend
    restart: unless-stopped
    ports:
      - '3010:3000'
      - '25:25'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=urbansend-super-secret-jwt-key-production-2024
      - JWT_EXPIRES_IN=7d
      - REDIS_HOST=urbansend_redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=https://www.urbanmail.com.br
      - DATABASE_URL=/app/database.sqlite
      - FRONTEND_URL=https://www.urbanmail.com.br
      - SMTP_HOSTNAME=www.urbanmail.com.br
    volumes:
      - urbansend_backend_data:/app/data
      - urbansend_backend_logs:/app/logs
    depends_on:
      - urbansend_redis
    networks:
      - urbansend_network

  urbansend_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: urbansend_frontend
    restart: unless-stopped
    ports:
      - '3011:80'
    depends_on:
      - urbansend_backend
    networks:
      - urbansend_network

  urbansend_redis:
    image: redis:7-alpine
    container_name: urbansend_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - urbansend_redis_data:/data
    ports:
      - '6380:6379'
    networks:
      - urbansend_network

  urbansend_redis_ui:
    image: rediscommander/redis-commander:latest
    container_name: urbansend_redis_ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:urbansend_redis:6379
    ports:
      - '8082:8081'
    depends_on:
      - urbansend_redis
    networks:
      - urbansend_network
