
services:
  urbansend:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: urbansend_app
    restart: unless-stopped
    ports:
      - "3010:3010"
      - "25:25"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3010}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - REDIS_HOST=${REDIS_HOST:-urbansend_redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - DATABASE_URL=${DATABASE_URL:-/app/data/database.sqlite}
      - FRONTEND_URL=${FRONTEND_URL}
      - SMTP_HOSTNAME=${SMTP_HOSTNAME}
      - SMTP_SERVER_PORT=${SMTP_SERVER_PORT:-25}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME:-UrbanSend}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs/app.log}
      - ERROR_LOG_PATH=${ERROR_LOG_PATH:-/app/logs/error.log}
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - UPLOAD_PATH=${UPLOAD_PATH:-/app/data/uploads}
      - SESSION_SECRET=${SESSION_SECRET}
      - BACKUP_ENABLED=${BACKUP_ENABLED:-true}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    depends_on:
      - redis
    networks:
      - urbansend_network
    labels:
      - "com.urbansend.service=app"
      - "com.urbansend.version=1.0.0"

  redis:
    image: redis:7-alpine
    container_name: urbansend_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - urbansend_network
    labels:
      - "com.urbansend.service=redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app_data:
    driver: local
    labels:
      - "com.urbansend.volume=data"
  app_logs:
    driver: local
    labels:
      - "com.urbansend.volume=logs"
  redis_data:
    driver: local
    labels:
      - "com.urbansend.volume=redis"

networks:
  urbansend_network:
    driver: bridge
    labels:
      - "com.urbansend.network=main"